name: Validação HTML

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  html-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4
      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - name: Instalar htmlhint
        run: |
          npm init -y > /dev/null 2>&1
          npm install --save-dev htmlhint@latest
      - name: Executar htmlhint
        run: npx htmlhint "**/*.html"
      - name: Publicar artefato de relatório (opcional se gerar futuramente)
        if: failure()
        run: echo "Falhas encontradas pelo htmlhint"
